# Generated by Django 6.0.6 on 2026-06-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('depaartment', models.CharField(max_length=50)),
                ('semester', models.IntegerField(max_length=1)),
                ('cgpa', models.FloatField(max_length=4)),
            ],
        ),
    ]
